### ISSUE TITLE
Сохранение результатов в БД

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/Agregator#13]
Результат парсинга страниц должен сохранятся в БД (СУБД можно выбрать самостоятельно)

**Comment by IgorKuzmenko** [comment]
Сохраняю в mongodb db = 'test'; collection= 'agregator'
Так как ссылки выбираются из сета(несортированный), по 8 шт(файле конфигурации) -  повторный запуск может привести к тому, что вновь будут добавлены страницы в базу. ->> Запускать несколько раз.
